### ISSUE TITLE
[enhancement] Expose plaintext versions of the files, let us compile them

### ISSUE THREAD

**Issue by mpr1255** [jpuris/apple-hide-my-email-shortcut-alfred#1]
Really great little project. Thank you for working on it. 

Is it possible to make available the actual AppleScript as well as a non-binary version of the Alfred Workflow? Right now there are two binary assets and we basically have to take it on faith that they are what they appear to be. 

I know this is more work. Apologies. This is a great tool.

**Comment by jpuris** [comment]
Heya! Just to elaborate.. the Alfred workflow simply runs the Apple shortcuts app. I can add the source to the apple script, but one can always simply open up the Apple shortcut (which you need to do anyway), and inspect it.

Let me know, if adding the AppleScript code seperately would be helpful to you.

**Comment by mpr1255** [comment]
Indeed. Totally my bad. One has to authorise it before being able to actually SEE it. Once I figured out that this was a non issue I closed this “issue” sheepishly. It’s a great workflow. Thanks.
